'use client'

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Logoroom(props) {
  const { nodes, materials } = useGLTF('/models/logoroom.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[19.188, 3.1, 7.303]} rotation={[-0.355, 0.59, -1.312]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Skateboard_1.geometry}
          material={materials.Skateboard_Mat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Skateboard_2.geometry}
          material={materials['08___Default']}
        />
      </group>
      <group position={[1.262, 6.292, 7.39]} rotation={[-1.562, -0.007, 2.927]} scale={-0.337}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.IMac_01_Cube026_1.geometry}
          material={materials.FFFFFF}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.IMac_01_Cube026_2.geometry}
          material={materials['1A1A1A']}
        />
      </group>
      <group
        position={[1.664, 6.247, 9.765]}
        rotation={[-Math.PI, 0.79, -Math.PI]}
        scale={[-1.642, -0.057, -0.536]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group1030983910.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group1075691498.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group1149852049.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group1152190519.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group1180881246.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group1238060299.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group1238428394.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group1272091893.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group1316349499.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group1323238240.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group145618305.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group1486350934.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group150579309.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group1529968652.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group1571332333.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group1581414308.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group1589752359.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group1629393722.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group1629609685.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group1675960081.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group1740918352.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group1753917514.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group1754683637.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group1764140354.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group1870575723.geometry}
          material={materials.mat16}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group1899843208.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group1956214489.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group196400395.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group1976194690.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group205302596.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group2074153597.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group2085389804.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group2091112366.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group2106755496.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group2146178072.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group252681800.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group268332703.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group287159489.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group295085766.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group311988427.geometry}
          material={materials.mat22}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group34220672.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group384612072.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group418912012.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group42243725.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group425587018.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group449779970.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group45382983.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group475225180.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group573547017.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group588539140.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group601803475.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group616518658.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group687259746.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group706802639.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group729811280.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group77921105.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group790925258.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group801095923.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group806343109.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group826580911.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group873458270.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group873558583.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group877249531.geometry}
          material={materials.mat9}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group954813675.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group96314515.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group96968687.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group993315105.geometry}
          material={materials.mat21}
          position={[-0.03, -0.515, -0.063]}
          rotation={[1.571, -0.012, 3.127]}
          scale={[-0.789, -2.419, -22.589]}
        />
      </group>
      <group position={[4.753, 6.165, 10.319]} rotation={[Math.PI / 2, 0, 0.807]} scale={0.23}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laptop_01_Cube025_1.geometry}
          material={materials.metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laptop_01_Cube025_2.geometry}
          material={materials['1A1A1A']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ComputerMouse.geometry}
        material={materials.FFFFFF}
        position={[3.461, 6.052, 11.565]}
        rotation={[Math.PI / 2, 0, -2.58]}
        scale={0.212}
      />
      <group position={[10.938, 10.128, 3.688]} rotation={[Math.PI / 2, 0, 2.36]} scale={0.066}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['1345_Analog_Clock_1'].geometry}
          material={materials.metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['1345_Analog_Clock_2'].geometry}
          material={materials['1A1A1A']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ElectricGuitar.geometry}
        material={materials.lambert2SG}
        position={[-15.559, 0.131, 1.191]}
        rotation={[1.511, 0.468, -1.439]}
        scale={0.465}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve.geometry}
        material={materials['SVGMat.008']}
        position={[-28.053, 0.04, 16.653]}
        scale={[133.812, 167.414, 133.812]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve005.geometry}
        material={materials['SVGMat.008']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve006.geometry}
        material={materials['SVGMat.008']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve007.geometry}
        material={materials['SVGMat.008']}
        position={[-28.053, 0.04, 16.653]}
        scale={[133.812, 236.792, 133.812]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve008.geometry}
        material={materials['SVGMat.008']}
        position={[-28.053, 0.04, 16.653]}
        scale={[133.812, 158.822, 133.812]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve009.geometry}
        material={materials['SVGMat.008']}
        position={[-28.053, 0.04, 16.653]}
        scale={[133.812, 285.809, 133.812]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve010.geometry}
        material={materials['SVGMat.008']}
        position={[-28.053, 0.04, 16.653]}
        scale={[133.812, 79.598, 133.812]}
      />
    </group>
  )
}

useGLTF.preload('/models/logoroom.glb')

