'use client'

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations} from '@react-three/drei'

export function Me(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/me.glb')
  const { actions } = useAnimations(animations, group)


  useEffect(() => {
    actions["Armature|mixamo.com|Layer0"].play();
  }, [actions]);
return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="arm_left">
            <skinnedMesh
              name="arm_leftmesh"
              geometry={nodes.arm_leftmesh.geometry}
              material={materials.skin}
              skeleton={nodes.arm_leftmesh.skeleton}
            />
            <skinnedMesh
              name="arm_leftmesh_1"
              geometry={nodes.arm_leftmesh_1.geometry}
              material={materials.black}
              skeleton={nodes.arm_leftmesh_1.skeleton}
            />
          </group>
          <group name="arm_right">
            <skinnedMesh
              name="arm_rightmesh"
              geometry={nodes.arm_rightmesh.geometry}
              material={materials.skin}
              skeleton={nodes.arm_rightmesh.skeleton}
            />
            <skinnedMesh
              name="arm_rightmesh_1"
              geometry={nodes.arm_rightmesh_1.geometry}
              material={materials.black}
              skeleton={nodes.arm_rightmesh_1.skeleton}
            />
          </group>
          <skinnedMesh
            name="beard"
            geometry={nodes.beard.geometry}
            material={materials.black}
            skeleton={nodes.beard.skeleton}
          />
          <group name="body">
            <skinnedMesh
              name="bodymesh"
              geometry={nodes.bodymesh.geometry}
              material={materials['dark-grey']}
              skeleton={nodes.bodymesh.skeleton}
            />
            <skinnedMesh
              name="bodymesh_1"
              geometry={nodes.bodymesh_1.geometry}
              material={materials.black}
              skeleton={nodes.bodymesh_1.skeleton}
            />
          </group>
          <skinnedMesh
            name="eyebrow_left"
            geometry={nodes.eyebrow_left.geometry}
            material={materials.black}
            skeleton={nodes.eyebrow_left.skeleton}
          />
          <skinnedMesh
            name="eyebrow_right"
            geometry={nodes.eyebrow_right.geometry}
            material={materials.black}
            skeleton={nodes.eyebrow_right.skeleton}
          />
          <skinnedMesh
            name="eyes"
            geometry={nodes.eyes.geometry}
            material={materials.black}
            skeleton={nodes.eyes.skeleton}
          />
          <skinnedMesh
            name="glasses"
            geometry={nodes.glasses.geometry}
            material={materials.black}
            skeleton={nodes.glasses.skeleton}
          />
          <skinnedMesh
            name="hairs"
            geometry={nodes.hairs.geometry}
            material={materials.black}
            skeleton={nodes.hairs.skeleton}
          />
          <skinnedMesh
            name="head"
            geometry={nodes.head.geometry}
            material={materials.skin}
            skeleton={nodes.head.skeleton}
          />
          <skinnedMesh
            name="leg_left"
            geometry={nodes.leg_left.geometry}
            material={materials['dark-grey']}
            skeleton={nodes.leg_left.skeleton}
          />
          <skinnedMesh
            name="leg_right"
            geometry={nodes.leg_right.geometry}
            material={materials['dark-grey']}
            skeleton={nodes.leg_right.skeleton}
          />
          <group name="shoe_left">
            <skinnedMesh
              name="shoe_leftmesh"
              geometry={nodes.shoe_leftmesh.geometry}
              material={materials.black}
              skeleton={nodes.shoe_leftmesh.skeleton}
            />
            <skinnedMesh
              name="shoe_leftmesh_1"
              geometry={nodes.shoe_leftmesh_1.geometry}
              material={materials.white}
              skeleton={nodes.shoe_leftmesh_1.skeleton}
            />
          </group>
          <group name="shoe_right">
            <skinnedMesh
              name="shoe_rightmesh"
              geometry={nodes.shoe_rightmesh.geometry}
              material={materials.black}
              skeleton={nodes.shoe_rightmesh.skeleton}
            />
            <skinnedMesh
              name="shoe_rightmesh_1"
              geometry={nodes.shoe_rightmesh_1.geometry}
              material={materials.white}
              skeleton={nodes.shoe_rightmesh_1.skeleton}
            />
          </group>
          <primitive object={nodes.mixamorigHips} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/me.glb')
