'use client'

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations} from '@react-three/drei'

export function Me(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/me.glb')
  const { actions } = useAnimations(animations, group)


  useEffect(() => {
    actions["Armature|mixamo.com|Layer0"].play();
  }, [actions]);


  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="arm_left">
            <skinnedMesh
              name="group4920458"
              geometry={nodes.group4920458.geometry}
              material={materials.mat18}
              skeleton={nodes.group4920458.skeleton}
              castShadow
              receiveShadow
            />
            <skinnedMesh
              name="group4920458_1"
              geometry={nodes.group4920458_1.geometry}
              material={materials.mat21}
              skeleton={nodes.group4920458_1.skeleton}
              castShadow
              receiveShadow
            />
          </group>
          <group name="arm_right">
            <skinnedMesh
              name="group1155631885"
              geometry={nodes.group1155631885.geometry}
              material={materials.mat18}
              skeleton={nodes.group1155631885.skeleton}
              castShadow
              receiveShadow
            />
            <skinnedMesh
              name="group1155631885_1"
              geometry={nodes.group1155631885_1.geometry}
              material={materials.mat21}
              skeleton={nodes.group1155631885_1.skeleton}
              castShadow
              receiveShadow
            />
          </group>
          <skinnedMesh
            name="beard"
            geometry={nodes.beard.geometry}
            material={materials.mat23}
            skeleton={nodes.beard.skeleton}
            castShadow
              receiveShadow
          />
          <group name="body">
            <skinnedMesh
              name="group1524745835"
              geometry={nodes.group1524745835.geometry}
              material={materials.mat23}
              skeleton={nodes.group1524745835.skeleton}
              castShadow
              receiveShadow
            />
            <skinnedMesh
              name="group1524745835_1"
              geometry={nodes.group1524745835_1.geometry}
              material={materials.mat17}
              skeleton={nodes.group1524745835_1.skeleton}
              castShadow
              receiveShadow
            />
          </group>
          <skinnedMesh
            name="eyebrow_left"
            geometry={nodes.eyebrow_left.geometry}
            material={materials.mat23}
            skeleton={nodes.eyebrow_left.skeleton}
            castShadow
              receiveShadow
          />
          <skinnedMesh
            name="eyebrow_right"
            geometry={nodes.eyebrow_right.geometry}
            material={materials.mat23}
            skeleton={nodes.eyebrow_right.skeleton}
            castShadow
              receiveShadow
          />
          <skinnedMesh
            name="eyes"
            geometry={nodes.eyes.geometry}
            material={materials.mat23}
            skeleton={nodes.eyes.skeleton}
            castShadow
              receiveShadow
          />
          <skinnedMesh
            name="glasses"
            geometry={nodes.glasses.geometry}
            material={materials.mat23}
            skeleton={nodes.glasses.skeleton}
            castShadow
              receiveShadow
          />
          <skinnedMesh
            name="group76706235"
            geometry={nodes.group76706235.geometry}
            material={materials.mat17}
            skeleton={nodes.group76706235.skeleton}
            castShadow
              receiveShadow
          />
          <skinnedMesh
            name="hairs"
            geometry={nodes.hairs.geometry}
            material={materials.mat23}
            skeleton={nodes.hairs.skeleton}
            castShadow
              receiveShadow
          />
          <skinnedMesh
            name="head"
            geometry={nodes.head.geometry}
            material={materials.mat18}
            skeleton={nodes.head.skeleton}
            castShadow
              receiveShadow
          />
          <skinnedMesh
            name="leg_left"
            geometry={nodes.leg_left.geometry}
            material={materials.mat17}
            skeleton={nodes.leg_left.skeleton}
            castShadow
              receiveShadow
          />
          <skinnedMesh
            name="leg_right"
            geometry={nodes.leg_right.geometry}
            material={materials.mat17}
            skeleton={nodes.leg_right.skeleton}
            castShadow
              receiveShadow
          />
          <group name="shoe_left">
            <skinnedMesh
              name="group1754668845"
              geometry={nodes.group1754668845.geometry}
              material={materials.mat21}
              skeleton={nodes.group1754668845.skeleton}
              castShadow
              receiveShadow
            />
            <skinnedMesh
              name="group1754668845_1"
              geometry={nodes.group1754668845_1.geometry}
              material={materials.mat22}
              skeleton={nodes.group1754668845_1.skeleton}
              castShadow
              receiveShadow
            />
            <skinnedMesh
              name="group1754668845_2"
              geometry={nodes.group1754668845_2.geometry}
              material={materials.mat15}
              skeleton={nodes.group1754668845_2.skeleton}
              castShadow
              receiveShadow
            />
          </group>
          <group name="shoe_right">
            <skinnedMesh
              name="group976850016"
              geometry={nodes.group976850016.geometry}
              material={materials.mat21}
              skeleton={nodes.group976850016.skeleton}
              castShadow
              receiveShadow
            />
            <skinnedMesh
              name="group976850016_1"
              geometry={nodes.group976850016_1.geometry}
              material={materials.mat22}
              skeleton={nodes.group976850016_1.skeleton}
              castShadow
              receiveShadow
            />
            <skinnedMesh
              name="group976850016_2"
              geometry={nodes.group976850016_2.geometry}
              material={materials.mat15}
              skeleton={nodes.group976850016_2.skeleton}
              castShadow
              receiveShadow
            />
          </group>
          <primitive object={nodes.mixamorigHips} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/me.glb')
